# config/temas.py
"""Define as paletas de cores disponíveis para o app."""

TEMAS = {
    "esmeralda": {
        "nome": "Esmeralda",
        "descricao": "Verde esmeralda com dourado - clássico financeiro",
        "seed": "emerald",
        "claro": {
            "sidebar_fundo": "#2E7D5B",
            "sidebar_borda": "#C9A961",
            "logo_fundo": "#1a4d3a",
            "logo_icone": "#F5E6A8",
            "logo_texto": "#FFFFFF",
            "menu_label": "#F5E6A8",
            "botao_ativo": "#F5E6A8",
            "botao_ativo_texto": "#1a4d3a",
            "botao_normal_icone": "#F5E6A8",
            "botao_normal_texto": "#FFFFFF",
            "tema_label": "#F5E6A8",
            "preview_cores": ["#2E7D5B", "#C9A961", "#F5E6A8"],
        },
        "escuro": {
            "sidebar_fundo": "#1a3d2e",
            "sidebar_borda": "#D4AF37",
            "logo_fundo": "#0d1f18",
            "logo_icone": "#D4AF37",
            "logo_texto": "#D4AF37",
            "menu_label": "#D4AF37",
            "botao_ativo": "#D4AF37",
            "botao_ativo_texto": "#1a3d2e",
            "botao_normal_icone": "#E8D5A0",
            "botao_normal_texto": "#F5F5F5",
            "tema_label": "#E8D5A0",
            "preview_cores": ["#1a3d2e", "#D4AF37", "#E8D5A0"],
        },
    },
    "oceano": {
        "nome": "Oceano",
        "descricao": "Azul marinho profundo com prata - corporativo",
        "seed": "blue",
        "claro": {
            "sidebar_fundo": "#1e3a5f",
            "sidebar_borda": "#A8B5C7",
            "logo_fundo": "#0f1f33",
            "logo_icone": "#E8EEF5",
            "logo_texto": "#FFFFFF",
            "menu_label": "#E8EEF5",
            "botao_ativo": "#E8EEF5",
            "botao_ativo_texto": "#0f1f33",
            "botao_normal_icone": "#E8EEF5",
            "botao_normal_texto": "#FFFFFF",
            "tema_label": "#E8EEF5",
            "preview_cores": ["#1e3a5f", "#A8B5C7", "#E8EEF5"],
        },
        "escuro": {
            "sidebar_fundo": "#0a1929",
            "sidebar_borda": "#C9A961",
            "logo_fundo": "#050d17",
            "logo_icone": "#C9A961",
            "logo_texto": "#C9A961",
            "menu_label": "#C9A961",
            "botao_ativo": "#C9A961",
            "botao_ativo_texto": "#0a1929",
            "botao_normal_icone": "#A8B5C7",
            "botao_normal_texto": "#E8E8E8",
            "tema_label": "#A8B5C7",
            "preview_cores": ["#0a1929", "#C9A961", "#A8B5C7"],
        },
    },
    "rubi": {
        "nome": "Rubi",
        "descricao": "Vinho sofisticado com rosa claro - elegante",
        "seed": "red",
        "claro": {
            "sidebar_fundo": "#6d1f2f",
            "sidebar_borda": "#E8B4BC",
            "logo_fundo": "#3d0f1a",
            "logo_icone": "#F5D5DB",
            "logo_texto": "#FFFFFF",
            "menu_label": "#F5D5DB",
            "botao_ativo": "#F5D5DB",
            "botao_ativo_texto": "#3d0f1a",
            "botao_normal_icone": "#F5D5DB",
            "botao_normal_texto": "#FFFFFF",
            "tema_label": "#F5D5DB",
            "preview_cores": ["#6d1f2f", "#E8B4BC", "#F5D5DB"],
        },
        "escuro": {
            "sidebar_fundo": "#3d0f1a",
            "sidebar_borda": "#E8B4BC",
            "logo_fundo": "#1f070d",
            "logo_icone": "#E8B4BC",
            "logo_texto": "#E8B4BC",
            "menu_label": "#E8B4BC",
            "botao_ativo": "#E8B4BC",
            "botao_ativo_texto": "#3d0f1a",
            "botao_normal_icone": "#D4A0A8",
            "botao_normal_texto": "#F5F5F5",
            "tema_label": "#D4A0A8",
            "preview_cores": ["#3d0f1a", "#E8B4BC", "#D4A0A8"],
        },
    },
    "amora": {
        "nome": "Amora",
        "descricao": "Roxo profundo com lilás - moderno e criativo",
        "seed": "purple",
        "claro": {
            "sidebar_fundo": "#4a2c6d",
            "sidebar_borda": "#C8B4E0",
            "logo_fundo": "#2a1840",
            "logo_icone": "#E8D5F5",
            "logo_texto": "#FFFFFF",
            "menu_label": "#E8D5F5",
            "botao_ativo": "#E8D5F5",
            "botao_ativo_texto": "#2a1840",
            "botao_normal_icone": "#E8D5F5",
            "botao_normal_texto": "#FFFFFF",
            "tema_label": "#E8D5F5",
            "preview_cores": ["#4a2c6d", "#C8B4E0", "#E8D5F5"],
        },
        "escuro": {
            "sidebar_fundo": "#2a1840",
            "sidebar_borda": "#C8B4E0",
            "logo_fundo": "#150c20",
            "logo_icone": "#C8B4E0",
            "logo_texto": "#C8B4E0",
            "menu_label": "#C8B4E0",
            "botao_ativo": "#C8B4E0",
            "botao_ativo_texto": "#2a1840",
            "botao_normal_icone": "#A890C8",
            "botao_normal_texto": "#F5F5F5",
            "tema_label": "#A890C8",
            "preview_cores": ["#2a1840", "#C8B4E0", "#A890C8"],
        },
    },
    "sunset": {
        "nome": "Sunset",
        "descricao": "Laranja coral com creme - quente e acolhedor",
        "seed": "orange",
        "claro": {
            "sidebar_fundo": "#c65d3a",
            "sidebar_borda": "#F5D5A8",
            "logo_fundo": "#7a3520",
            "logo_icone": "#FFF0D5",
            "logo_texto": "#FFFFFF",
            "menu_label": "#FFF0D5",
            "botao_ativo": "#FFF0D5",
            "botao_ativo_texto": "#7a3520",
            "botao_normal_icone": "#FFF0D5",
            "botao_normal_texto": "#FFFFFF",
            "tema_label": "#FFF0D5",
            "preview_cores": ["#c65d3a", "#F5D5A8", "#FFF0D5"],
        },
        "escuro": {
            "sidebar_fundo": "#7a3520",
            "sidebar_borda": "#F5D5A8",
            "logo_fundo": "#3d1a10",
            "logo_icone": "#F5D5A8",
            "logo_texto": "#F5D5A8",
            "menu_label": "#F5D5A8",
            "botao_ativo": "#F5D5A8",
            "botao_ativo_texto": "#7a3520",
            "botao_normal_icone": "#D4B890",
            "botao_normal_texto": "#F5F5F5",
            "tema_label": "#D4B890",
            "preview_cores": ["#7a3520", "#F5D5A8", "#D4B890"],
        },
    },
    "noir": {
        "nome": "Noir",
        "descricao": "Preto profundo com dourado - ultra premium",
        "seed": "amber",
        "claro": {
            "sidebar_fundo": "#2a2a2a",
            "sidebar_borda": "#D4AF37",
            "logo_fundo": "#0d0d0d",
            "logo_icone": "#D4AF37",
            "logo_texto": "#D4AF37",
            "menu_label": "#D4AF37",
            "botao_ativo": "#D4AF37",
            "botao_ativo_texto": "#0d0d0d",
            "botao_normal_icone": "#E8D5A0",
            "botao_normal_texto": "#F5F5F5",
            "tema_label": "#E8D5A0",
            "preview_cores": ["#2a2a2a", "#D4AF37", "#E8D5A0"],
        },
        "escuro": {
            "sidebar_fundo": "#0d0d0d",
            "sidebar_borda": "#D4AF37",
            "logo_fundo": "#000000",
            "logo_icone": "#D4AF37",
            "logo_texto": "#D4AF37",
            "menu_label": "#D4AF37",
            "botao_ativo": "#D4AF37",
            "botao_ativo_texto": "#000000",
            "botao_normal_icone": "#E8D5A0",
            "botao_normal_texto": "#FFFFFF",
            "tema_label": "#E8D5A0",
            "preview_cores": ["#0d0d0d", "#D4AF37", "#E8D5A0"],
        },
    },
}

TEMA_PADRAO = "esmeralda"